name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the latest bandit image
      run: docker build . --file Dockerfile --tag eracorp/bandit:$(date +%s)
